# permissions for end users to view customimagedeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customimagedeploy-viewer-role
rules:
- apiGroups:
  - customimagedeploy.example.com
  resources:
  - customimagedeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - customimagedeploy.example.com
  resources:
  - customimagedeploys/status
  verbs:
  - get
